### ISSUE TITLE
KH1(FM) - Difficulty Change

### ISSUE THREAD

**Issue by ProjectXsent** [Xeeynamo/KH3SaveEditor#100]
Game name: - Kingdom Hearts 1 / Kingdom Hearts 1 Final Mix
Platform: - (eg. PC, PS2, etc.) - Any
--- insert your feature request description here---
I have successfully imported my KH1 progress to KHFM. I change the difficulty option to Final Mix: Proud but says Final Mix: Beginner in-game.

**Comment by Xeeynamo** [comment]
Fixed. You can download it the latest release. Thanks for the feedback!
