### ISSUE TITLE
Dragon age inquisition 

### ISSUE THREAD

**Issue by Kidakakash** [Xeeynamo/KH3SaveEditor#102]
* Game name: - Dragon age inquisition 
* Platform: - (eg. PC, PS2, etc.) PS4

--- insert your feature request description here---
Do you think you could make a save editor for dragon age inquisition on PS4 to modify the numbers of : influence bar, inquisition power point, inqusition perk point, skill point, money and add most invotory ?

Please

cordially

Kida

**Comment by Xeeynamo** [comment]
Hi, I do not think I will as I never played that game. Sorry.
