### ISSUE TITLE
Save editor doesn't open

### ISSUE THREAD

**Issue by StarCracks** [Xeeynamo/KH3SaveEditor#104]
For some reason, version 13 and 13.1 don't open on my pc and I don't know why. It is very odd. Can you help in any way?

**Comment by Xeeynamo** [comment]
Hi. If you open to Event Viewer on your Windows, in Windows Logs and then Applications you might find an error on why the editor does not open on your configuration.

Also, what operating system do you use? Do you have any antivirus that might stop the execution of downloaded software?

**Comment by Xeeynamo** [comment]
I published a new version. Does it work for you?

**Comment by Xeeynamo** [comment]
Closed due to inactivity
