### ISSUE TITLE
Buffer size issue

### ISSUE THREAD

**Issue by alguse** [Xeeynamo/KH3SaveEditor#106]
![IMG_3434](https://user-images.githubusercontent.com/10273345/99194572-d1bd4180-2745-11eb-8e45-179db1e45a16.jpg)
Hi!
Every time I run the app and save (even without making any changes) I get "BufferSize must be greater than zero. Parameter name: bufferSize "

Could I be missing something??

**Comment by Xeeynamo** [comment]
Sorry, could you download the save editor again? It was an oversight I fixed literally 5 minutes ago.

**Comment by alguse** [comment]
yes, it's working now, however my mods don't reflect on my save data... I'll have to play a little more with this I guess.
Thanks
