### ISSUE TITLE
KH1FM - Ability Modification: Missing Ability

### ISSUE THREAD

**Issue by RaXZerGamingZ** [Xeeynamo/KH3SaveEditor#107]
* Game name: Kingdom Hearts Final Mix (HD 1.5)
* Platform: - PS3, PS4

Recently Ability Modification was added for KH1, the Combo Master ability is missing. (shows blank if loading a file where Sora has it, and is not in the list of abilities.)

**Comment by Xeeynamo** [comment]
I recently became aware that Combo Master is an exclusive ability of Kingdom Hearts 1: Final Mix for PS3 and PS4 🤔

**Comment by RaXZerGamingZ** [comment]
Yes and EXP Zero too, that one is in the Save Editor

**Comment by Xeeynamo** [comment]
Fixed in the latest version
