### ISSUE TITLE
KH3 - Experience Multiplier

### ISSUE THREAD

**Issue by nidetech** [Xeeynamo/KH3SaveEditor#109]
Kingdom Hearts 3
PlayStation 4 

Would it be possible to add a experience multipler that changes the amount of exp that is dropped? So this makes it a lot easier to grind but doesn't shoot me all the way up to level 99, and still makes it feel like I'm playing the game. 

And maybe also adding a drop multiplier if its not too much too ask.

I assume this feature would have a 1x, 2x, 4x, 8x, 16x, 32x, exp multiplier option. Please let me know if this is possible because then I would love to come back to the game and start over. <3

**Comment by Xeeynamo** [comment]
Hi, this is not something it is possible to do via save editing as the game does not store such information in it. You have to modify game's files, which is out of scope in this project. Sorry. Closing.
