### ISSUE TITLE
Not supported with KH3 Re:Mind DLC Saves

### ISSUE THREAD

**Issue by laurensarah2022** [Xeeynamo/KH3SaveEditor#11]
The save editor is no longer compatible with the latest save files from the latest DLC Re:Mind, if you try and open a data0-2.bin file from the latest save version the program will exit without any notification.

No error appears, however seeing as how the data.bin files worked perfectly fine prior to being updated to the latest DLC, I suspect that this save editor hasn't been updated to support the latest changes with the DLC.

**Comment by LoneFuckingWolf** [comment]
Yeah. I hope it'll get updated soon.

**Comment by LoneFuckingWolf** [comment]
New version released. Problem solved.

**Comment by laurensarah2022** [comment]
Awesome I'll have to test it when I get home.

**Comment by Xeeynamo** [comment]
Happy to see that everything is now working for you guys! I am closing this issue :)
