### ISSUE TITLE
Dream drop distance- not recognized

### ISSUE THREAD

**Issue by shadowsofyggdrasil** [Xeeynamo/KH3SaveEditor#115]
Dream drop distance
PS4

I tried to load my decrypted save (I used save wizard to decrypt it) and it says it's not recognized, but on your front page you list all versions of DDD as workable, so I don't know if this a mistake, bug, or feature request tbh.

**Comment by Xeeynamo** [comment]
It is implemented in the source code, but if you see the application when running that KH DDD is not there. Meaning that only the new version will have it once I will release it.
