### ISSUE TITLE
Program Wont Open

### ISSUE THREAD

**Issue by raynelogens** [Xeeynamo/KH3SaveEditor#116]
I have installled .NET Framework as instructed but the program still wont open. I keep getting the error message attached. What can I do? Any help please?????
![Capture](https://user-images.githubusercontent.com/43230780/103323877-da768800-4a12-11eb-8d00-5541c9d996cd.PNG)

**Comment by Topaz-Reality** [comment]
Your system is 32-bits. This program is pre-compiled for 64-bits only.
Either reinstall Windows, or try to compile this program yourself for 64-bits, or use this program on a 64-bit computer.
Proposing a closure of this issue. @Xeeynamo

**Comment by Xeeynamo** [comment]
64 bit only, sorry.
