### ISSUE TITLE
Persona 5 Royal 

### ISSUE THREAD

**Issue by khen90** [Xeeynamo/KH3SaveEditor#117]
Persona 5 Royal
Read p5 error bug
hi,just to let you know that the read p5 error still occur when opening a decrypted save of P5R thanks.

**Comment by Xeeynamo** [comment]
Could you attach your save?

**Comment by khen90** [comment]
[DATA.zip](https://github.com/Xeeynamo/KH3SaveEditor/files/5759913/DATA.zip)

**Comment by khen90** [comment]
[CUSA17416.zip](https://github.com/Xeeynamo/KH3SaveEditor/files/5761087/CUSA17416.zip)

i upload this just in case you need a proper save

**Comment by Xeeynamo** [comment]
Sorry for getting in touch so late. I was able to spot the bug and load your save. Expect a new release of the save editor very shortly. Sorry about the problem it caused.
![image](https://user-images.githubusercontent.com/6128729/104040646-d2b3a200-51cf-11eb-81ca-8c463eb488a0.png)

**Comment by khen90** [comment]
hi again,i downloaded and tested your newest release of the editor and unfortunately it still gives the error. what might caused the problem or this release of the editor does not include the fix yet? Thanks again.

**Comment by Xeeynamo** [comment]
> hi again,i downloaded and tested your newest release of the editor and unfortunately it still gives the error. what might caused the problem or this release of the editor does not include the fix yet? Thanks again.

Please try this one: https://github.com/Xeeynamo/KH3SaveEditor/releases/tag/v1.14.5

**Comment by khen90** [comment]
hi, i tested the newest release and its working now so i'm going to close this issue then. thanks so much and stay safe 👍

**Comment by Xeeynamo** [comment]
Cool beans. Enjoy it and stay safe you too 🙂
