### ISSUE TITLE
Kingdom Hearts 1.5 Save Transfer to upcoming PC release?

### ISSUE THREAD

**Issue by CriticalComposer** [Xeeynamo/KH3SaveEditor#126]
* Kingdom Hearts 1.5: -
* PS4, PC

Are there any intentions to update this software to support the upcoming PC releases of 1.5, 2.5, 2.8, and 3? I'm not even too concerned about modifying the save file as much as I am looking to import a PS4 save and export it into a PC save. I'm kinda hoping it won't require any modification at all but I understand that is probably a pipe dream so I'm looking into any software developers that understand how the saves work and hoping to find someone who's as interested as I am at continuing their save files between platforms.

**Comment by Delta-473** [comment]
It's probably wrapped into yet another container format, so if you can provide a couple of saves when it comes out that would be great. As I'm not buying it at launch, other devs might get it at launch.

**Comment by Xeeynamo** [comment]
Too soon to know anything about it really. But PC release will be supported no matter what.

**Comment by RaXZerGamingZ** [comment]
In Final Fantasy X the PC port can play PS4 saves, just decrypt them and put them in the Saves folder of the game. It could work the same with Kingdom Hearts.

**Comment by Rikux3** [comment]
Closing this cause latest release supports 1.5+2.5 and DDD
