### ISSUE TITLE
KHBBS - Missing voice in the reports

### ISSUE THREAD

**Issue by hoozyy** [Xeeynamo/KH3SaveEditor#128]
I was going to platinum khbbs on ps4, and when i finally end all of the three stories (at 100%) there were missing three voices on the terra's characters section (daisy duck, captain justice and the enchanted brooms, i discover that it was a bug cause they were all supposed to be discovered on the same scene). I don't know how to use the save editor, and neither can speak english very well, can somebody help me with fixing this (with the most basic words, thanks :) )?

**Comment by Delta-473** [comment]
If you need help for certain features pls ask them in the save editor Discord. As GitHub issues are for bug reporting or feature requests. Also idk what you mean with voices.
