### ISSUE TITLE
KH2(FM) - Weapon Model Swapping

### ISSUE THREAD

**Issue by RaXZerGamingZ** [Xeeynamo/KH3SaveEditor#130]
* Game name: - Kingdom Hearts 2 (Final Mix)
* Platform: - Any

To be able to swap the models of weapons. If it is unstable then atleast as an "Advanced" option.

**Comment by Delta-473** [comment]
You can't swap the model of a weapon with save editing. You can select a different weapon you use, if you want to change the model of a weapon you need to look at openKH tools. https://github.com/Xeeynamo/OpenKh

**Comment by Xeeynamo** [comment]
Not possible via save editing unfortunately
