### ISSUE TITLE
ps3 save-games

### ISSUE THREAD

**Issue by bucanero** [Xeeynamo/KH3SaveEditor#136]
hello @Xeeynamo 

I'm the developer of [Apollo Save Tool](https://github.com/bucanero/apollo-ps3), a PS3 homebrew to decrypt, patch, resign, checksum-fix, and edit ps3 save-games.

Just in case it might be helpful for your save editor, you can find some decryption/encryption/checksum tools for Final Fantasy XIII/ XIII-2 /X /X2 and some other games I reversed here:
https://github.com/bucanero/ps3-save-decrypters

I just found your editor and I'm going to include the KH2.5/BBS checksum fixing to Apollo. Thanks for sharing your code.

cheers 👋

**Comment by Xeeynamo** [comment]
Nice ✌
