### ISSUE TITLE
1.5-2.5 Saves are PC compatible

### ISSUE THREAD

**Issue by Danish127** [Xeeynamo/KH3SaveEditor#141]
* Game name: - 1.5+2.5 Collection
* Platform: - PC

I've done some datamining and have been able to import my Decrypted PS4 saves over to the pc version.
I've written a standalone tool for this, but I really think it would be better fit as a component of your tool.

I'm a little new to open source, so I don't know the best way of contacting y'all about this.

**Comment by Xeeynamo** [comment]
Hi, we already added support for those games. I just need to publish a new version. Please have a look on our [latest commits](https://github.com/Xeeynamo/KH3SaveEditor/commits/master).
