### ISSUE TITLE
Kingdom Hearts - Question about save converting

### ISSUE THREAD

**Issue by ejektaflex** [Xeeynamo/KH3SaveEditor#146]
* Kingdom Hearts 1.5+2.5 Remix

Just a question - can this be used to convert a save from KH1.5/2.5 on PS4 to PC?

**Comment by ejektaflex** [comment]
I've attempted this with an existing save from Save Wizard (advanced mode dump) and got this when I tried to import it:

![image](https://user-images.githubusercontent.com/23628421/113366331-7a97c200-931e-11eb-8149-c1b8cd648ea9.png)

**Comment by Xeeynamo** [comment]
you can only modify saves, not convert them.
