### ISSUE TITLE
Kingdom Hearts 3 + Re:Mind (PC - Epic Games)

### ISSUE THREAD

**Issue by Venipa** [Xeeynamo/KH3SaveEditor#150]
* Game name: Kingdom Hearts 3 + Re:Mind
* Platform: PC (Epic Games

Could you support the PC version's save file?

![image](https://user-images.githubusercontent.com/17952364/113421130-d455c600-93ca-11eb-9919-e7083350fad0.png)

**Comment by L1qu1d1c3** [comment]
Duplicate of #147
