### ISSUE TITLE
DLC Armors still misenumerated

### ISSUE THREAD

**Issue by Mirrorman95** [Xeeynamo/KH3SaveEditor#22]
The pull request didn't work. The changes I made to ArmorType and InventoryType weren't added into the latest master. I don't know what went wrong, but maybe it'd be easier if it they were just edited into the master branch directly. On line 178 of InventoryType.cs and line 74 of ArmorType.cs, add the line
`Item30,`
between the lines
`[Armor("Insulator Rosette")] InsulatorRosette,`
and
`[Armor("Power Weight")] en,`
or else Power Weight, Magic Weight, and Master Belt won't be listed right.
Also, remove ArmorType line 77,
`Item34,`
to compensate for the shift.

**Comment by Xeeynamo** [comment]
Oopsie, good point.
```csharp
[Armor("Insulator Rosette")] InsulatorRosette,
Item30,
[Armor("Power Weight")] en,
[Armor("Magic Weight")] en2,
[Armor("Master Belt")] en3,
Item35,
```

I imagine this is the change you mentioned.

Also what about `InventoryType.cs`? Should it have the same shift?

Thanks!

**Comment by Mirrorman95** [comment]
I literally mentioned InventoryType twice in my initial comment.

**Comment by Xeeynamo** [comment]
Sorry, It has been a long day 😄
