### ISSUE TITLE
Character tabs for the Keyblade Graveyard party members

### ISSUE THREAD

**Issue by LoneFuckingWolf** [Xeeynamo/KH3SaveEditor#24]
I apologise in advance if this is the wrong place to put this. I had no idea where else to put this because I'm a goddamn noob at github. If this is indeed the wrong place, just remove it.
In the Characters tab, there are missing slots for all the party members you get at the Keyblade Graveyard, such as Aqua, Ventus, Roxas, Lea, Kari and Xion. I understand it must be hard to implement their peripherals, but just in case you did not notice this, I've made this to point it out.
I'd like this added just so I could increase all of their defenses so they won't die to boss fights in the first 10 seconds after it starts.
Again, I apologise if this is the wrong place to put something like this.

**Comment by Xeeynamo** [comment]
I actually do not know if the character information are in the save... But I don't think so?? I will explore the save a bit more and let you know!

**Comment by LoneFuckingWolf** [comment]
Alright. Glad that you shed some light on the matter. Thanks dude.
