### ISSUE TITLE
I could use a bit of assistance, I am new to this. 

### ISSUE THREAD

**Issue by YomiRev** [Xeeynamo/KH3SaveEditor#26]
Okay so I believe that with this awesome save editor it was possible to edit Sora, Donald, Goofy and other party members to have more than the normal max amount of armour, Items and accessories. But as of late it hasn’t been working would someone be kind enough to explain what I am doing wrong? Thank you in advance and sorry if this is the incorrect section for this. I have been doing like I am had been except I just equipped Sora with all Royal Ribbons these past few times and the Regalia+ and MegaElixirs. Oh and to add further information I left Donald and Goofy and other party members alone completely. Okay I have tried again but now I cannot actually get the equipment slots to highlight, I am really not sure what I am doing wrong here. I have tried downloading it again when I could get the equipment slots to highlight I tried using other items so just regular potions basic armour’s and accessories that I KNEW I had. I am thinking that this is just me because I thought that I would have heard about it otherwise and I really am not sure what I am doing wrong here, I am not always with it as I am kept as medicated as possible so it’s USUALLY a me thing when I have something like this. I would really appreciate someone’s assistance if they would be so kind. Thank you and have a great day okay.

**Comment by Xeeynamo** [comment]
I am not sure to understand the issue
