### ISSUE TITLE
save editor questions from a noob 

### ISSUE THREAD

**Issue by hgfjrtzsrh** [Xeeynamo/KH3SaveEditor#27]
Sup man love the save editor helped me do a lot in kh3 I didn't know was even possible, I have one question though with the 1.9 update is it possible to add double form to the shortcut menu when I go to edit the shortcuts even with the latest editor I cant see anything past prism rain if its a dumb question or its not able to be done sorry I just wanted to know wanted to have it as a shortcut for the dlc data battles if Its possible thanks in advance love the work.

**Comment by YomiRev** [comment]
That would be awesome actually, I love the double form. Having it as a shortcut would be really really cool.

**Comment by Salbarwolf** [comment]
I hope it comes out as well. I can't wait to play with two Keyblades from the start. Sounds amazingly fun.

**Comment by Xeeynamo** [comment]
Do not worry, I got the request and it is already implemented in the next version! I just did not had time to test it properly. You will be notified here when the new version is ready to be released

**Comment by Xeeynamo** [comment]
Fixed in v1.9.1
