### ISSUE TITLE
How to open

### ISSUE THREAD

**Issue by Jryoda** [Xeeynamo/KH3SaveEditor#28]
couldn't open the program wich thing I need to use

**Comment by Xeeynamo** [comment]
Do you have any error when you try to open the software? I remember someone else had the same problem and it turned out it was his computer, since the Save Editor could be opened to any other computers.

**Comment by Jryoda** [comment]
no, I can't find the file to open it

**Comment by Jryoda** [comment]
no one wanna answer

**Comment by Xeeynamo** [comment]
![image](https://user-images.githubusercontent.com/6128729/76192633-33ea9d80-61da-11ea-9496-49a595eb69a3.png)
The one with the crown icon.
