### ISSUE TITLE
ArmorType Misenumerated

### ISSUE THREAD

**Issue by Mirrorman95** [Xeeynamo/KH3SaveEditor#31]
I noticed a small lingering error in \KHSave.Lib3\Types\ArmorType.cs and since it was just a few lines in one file, I thought it'd be easier to report as an issue than a pull request:
Change lines 74-77 from:
	    [Armor("Power Weight")] PowerWeight,
	    [Armor("Magic Weight")] MagicWeight,
	    [Armor("Master Belt")] MasterBelt,
	    Item34,
to:
	    Item31,
	    [Armor("Power Weight")] PowerWeight,
	    [Armor("Magic Weight")] MagicWeight,
	    [Armor("Master Belt")] MasterBelt,

Addendum:
Upon further review, it seems that part of the problem might've been that I mistakenly made a shift in \KHSave.Lib3\Types\InventoryType.cs when I should've only shifted ArmorType instead. It got added to the main branch in one of my previous Pull Request suggestions. So in addition to the above edit, Line 178 of InventoryType will have to be removed. It says:

Item174,

**Comment by Xeeynamo** [comment]
I Will look into that again :)

**Comment by Xeeynamo** [comment]
It should be fixed. I will re-open this in case it is not.
