### ISSUE TITLE
FF7 Remake new location request  (33200,14030,-29520)

### ISSUE THREAD

**Issue by bedbuggy** [Xeeynamo/KH3SaveEditor#33]
**Chapter**: `4`

**Coordinates**: `-58993.77, 14327.95, 4.136047`

**Short description**: Past invisible wall in Ch 4 by Jessie's House. Can freely walk on the otherwise of town we never get to go to. Can only walk on roads

Please also attach a screenshot, if possible, of the location you decided to request. You can find the coordinates to paste here on the Teleport window.

**Comment by Xeeynamo** [comment]
Always interesting to receive coordinates to go out of bounds :P. Thanks! It will be added to the next version :)
