### ISSUE TITLE
FF7R Missing item name request (Item ID 9060)

### ISSUE THREAD

**Issue by dave11674** [Xeeynamo/KH3SaveEditor#34]
Item name: `eg. Hi-Potion`

Before opening this issue, please be 100% sure that the item you are reporting is the correct one. 
To prove the item name, you can set a specific amount and see if in-game the value is there, or you set the amount of all your inventory to 0 but this item. The in-game inventory should be empty and the only item is the one you were searching for.

hi this item is the Gotterdammerung

9060 | 64230000 | 00002364 | Gotterdammerung | (Accessories)
-- | -- | -- | -- | --

please add to the editor, thanks

**Comment by Xeeynamo** [comment]
Done, it will be inserted in the next version. Thanks!
