### ISSUE TITLE
FF7 Remake new location request (27308.03,-114.6156,-29949.7)

### ISSUE THREAD

**Issue by bedbuggy** [Xeeynamo/KH3SaveEditor#37]
Chapter: `1-18`

Coordinates: (27308.03,-114.6156,-29949.7) 

Out of bounds: Yes

Short description: In front of Shinra HQ front door, small area to free roam

**Comment by Xeeynamo** [comment]
Changes are online! You will see the new location added auto-magically in the save editor 👍
