### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by jacopo-lupi** [Xeeynamo/KH3SaveEditor#39]
Salve, è possibile far girare il codice su Linux Ubuntu o altre distro?

**Comment by Xeeynamo** [comment]
Ciao Jacopo,

Il Save Editor funziona solo su salvataggi decriptati. I file decriptati si ottengono tramite Save Wizard, che e' Windows-only, quindi non avrebbe molto senso adattare il codice su Linux.

Ma ti diro' di piu': la UI e' Windows-only, pero' tutti i file di libreria (i parser) dei vari file di salvataggio sono cross-platform. Se hai un po' di dimestichezza col codice, puoi creare un command line tool per modificare i salvataggi su Linux.

Oppure esiste il progetto Wine su Linux. Chiudo l'issue, ma se hai ulteriori domande, posso rispondere.
