### ISSUE TITLE
crasha quando apro il save di kh3

### ISSUE THREAD

**Issue by gdfhdjnvmh** [Xeeynamo/KH3SaveEditor#4]
crasha quando apro il save di kh3

**Comment by Xeeynamo** [comment]
Ciao .

Riesci a darmi maggiori dettagli? Che nome ha il file che stai aprendo? Lo hai decriptato prima con Save Wizard? Che errore ti dà con il crash?

Grazie

Sent from Android

On 20 Apr 2019 13:13, gdfhdjnvmh <notifications@github.com> wrote:

crasha quando apro il save di kh3

**Comment by SilverCam** [comment]
> Ciao . Riesci a darmi maggiori dettagli? Che nome ha il file che stai aprendo? Lo hai decriptato prima con Save Wizard? Che errore ti dà con il crash? Grazie Sent from Android On 20 Apr 2019 13:13, gdfhdjnvmh <notifications@github.com> wrote: crasha quando apro il save di kh3

Hi Xeeynamo! What is the easiest way to contact you? I did some research for your save editor and would like to contribute.

**Comment by Xeeynamo** [comment]
@SilverCam Hi, for now just write me to _my nickname at hotmail.com_

**Comment by Xeeynamo** [comment]
@gdfhdjnvmh Novita'?

**Comment by Xeeynamo** [comment]
Closing for missing information about the crash issue.
