### ISSUE TITLE
Please add a KH3 Save Decrypt

### ISSUE THREAD

**Issue by Maskedtime** [Xeeynamo/KH3SaveEditor#42]
It would be nice to be able to decrypt my Kh3 save on your editor.

**Comment by Xeeynamo** [comment]
It is not possible as it would need a permanent jailbreak on PS4 (which I do not have). I considered it and I spoke with Save Wizard developers too and there is no way their decryption system will be public any time soon.

If something will change, I will immediately update the Save Editor.
