### ISSUE TITLE
KH RE:ChainMemories

### ISSUE THREAD

**Issue by stvjhr** [Xeeynamo/KH3SaveEditor#44]
Hi, for the editor KH Re:chain of memories, can you make something like exp editor ?

**Comment by Xeeynamo** [comment]
Hi, can you send me your save, specifying the amount of EXP that Sora (or Riku) have? I can look to add it ASAP.

**Comment by stvjhr** [comment]
Here i upload in the form of .DAT also the one from PS 4 direct.

[KH COM.zip](https://github.com/Xeeynamo/KH3SaveEditor/files/4550396/KH.COM.zip)

**Comment by Xeeynamo** [comment]
what's your current amount of exp?

**Comment by stvjhr** [comment]
For slot 1 the current exp 2566
Slot 3 current exp 256336

**Comment by stvjhr** [comment]
Sorry,

SLot 1 RIku 2566
Slot 3 Sora 256336

**Comment by Xeeynamo** [comment]
Ok, I am on it

**Comment by Xeeynamo** [comment]
The EXP mod for Re:CoM has been implemented! Please wait for the next version to receive the feature; it would require 7 days or less to be published :) . I will notify you here when the feature will be live!

![image](https://user-images.githubusercontent.com/6128729/80866264-a0879300-8c85-11ea-8c7d-c47b93623688.png)

**Comment by stvjhr** [comment]
Hi, 
Thank you, i just want to skip the grinding for exp, and perfect the game with new graphic.
already did COM long ago in GBA.

Just wanting to ask,
Is by any chance, you would do the editor for KH BBS?
just want to know, because same like COM, i already perfect the game long ago in PSP.
but want to make a PS4 save too.
but if i transferred the save data, my character is like ghost in mirage arena.
so if i have to play again, just want to to skip the grinding process

THank You

**Comment by Xeeynamo** [comment]
Yeah, importing BBS save on the remastered version can cause that problem. A suggestion I can give to you is to go on PSP, change your character colour to 200% and import the save again. The transparency issue will not be there.

There are no plans at the moment for Birth By Sleep editing functionalities, but it might change in the future!

**Comment by Xeeynamo** [comment]
@stvjhr I published a new version with the EXP modifier for RE: Chain of Memories 😁:
https://github.com/Xeeynamo/KH3SaveEditor/releases/tag/v.1.11.0
