### ISSUE TITLE
bin files wont load

### ISSUE THREAD

**Issue by shini199** [Xeeynamo/KH3SaveEditor#46]
when i try to load a save file for ff7r it says this file is not supported
![Untitled](https://user-images.githubusercontent.com/64566022/80661654-473d1b00-8a5d-11ea-9fe6-c8f08646c486.png)

**Comment by Xeeynamo** [comment]
It says that the save must be **decrypted** or supported. My very strong guess is that you did not decrypted the save. 

You have to follow the guide at the home page.
Spoiler alert: you need Save Wizard
