### ISSUE TITLE
Kingdom Hearts 1.5 editor?

### ISSUE THREAD

**Issue by Rhia12** [Xeeynamo/KH3SaveEditor#52]
I would love it if you would add the Kingdom Hearts 1.5 game (PS4) to this editor.

**Comment by Xeeynamo** [comment]
One of the contributors of this project just add Kingdom Hearts 1.5 support last week. I am finalising some stuff before releasing to the public. So hold on, it's coming :)

**Comment by Xeeynamo** [comment]
As promised: Kingdom Hearts 1: Final Mix save game editing support:
https://github.com/Xeeynamo/KH3SaveEditor/releases
