### ISSUE TITLE
[Issue] Can't add weapon Silver Staff.

### ISSUE THREAD

**Issue by bokkoman** [Xeeynamo/KH3SaveEditor#61]
I'm trying to add the Silver Staff for Aerith.
I put the staff in an empty slot at the bottom of the weapon list. Save the file and put it into savewizard to encrypt again.
But it doesn't add the weapon.
Adding materia works, though the AP level looks strange. It says AP 0/797080504, that can't be right.

**Comment by bokkoman** [comment]
I solved the AP error. I had to add them as level 1 materia. It was on 0 standard, which is not correct i think.

**Comment by Xeeynamo** [comment]
So can you confirm that adding the weapon to the Materia tab and assigning materia with the correct level just do the trick? I never tried to add weapons, but you might confirm that this is the way how it is supposed to work.
Thanks!

**Comment by bokkoman** [comment]
Well, i haven't been able to add the staff. I tried signing a materia to it, but that did not work. Maybe it is because there is only 1 in the game, and i haven't bought it from the moogle shop (i forgot). So the game thinks it is still in the shop as not bought?

I only fixed my AP level for EXP UP and AP UP.
I think you need to add materias always as level 1. The save editor adds them as level 0 by default, you have to manually edit this.

**Comment by Xeeynamo** [comment]
Hey, I released the new version 1.11.0. It fixes adding a weapon from the "Equipment" tab! If you continue to have any problems on adding a new weapon, I will open this Issue again.
