### ISSUE TITLE
Birth By Sleep editing

### ISSUE THREAD

**Issue by Lasareo** [Xeeynamo/KH3SaveEditor#62]
Is there any chance of BBS (PS4) editing coming? I'd like to be able to add things to my inventory or add different commands to my saves

**Comment by Xeeynamo** [comment]
Hello @Lasareo, sorry for coming back so late. Birth By Sleep editing functionality has been implemented by [Rikux3](https://github.com/sponsors/Rikux3) and it has been integrated in the latest version of the save editor: https://github.com/Xeeynamo/KH3SaveEditor/releases

Please enjoy 👍
