### ISSUE TITLE
How to use on Linux?

### ISSUE THREAD

**Issue by Klairm** [Xeeynamo/KH3SaveEditor#69]
Hello, is it possible to run this on Linux? If so, how? I  seen the readme says there's a shell script file for update the dependencies, but no more build instructions.

Thanks and stay safe!

**Comment by Xeeynamo** [comment]
Unfortunately the GUI will not run on Linux.
Although, the libraries to parse save files are cross-platform if you want to create a quick CLI tool to perform save editing.
