### ISSUE TITLE
Photo Data Broken

### ISSUE THREAD

**Issue by TiTan325** [Xeeynamo/KH3SaveEditor#7]
Hi, when im using the Delete-Function, from ur Editor, then the game is showing the Photos for the Lucky Emblems (in Gumifon) as a broken Data ;/

![broken data 1](https://user-images.githubusercontent.com/51882115/59565352-bdf24500-9052-11e9-84f0-c2bb1c762392.jpg)
![broken data 2](https://user-images.githubusercontent.com/51882115/59565353-c185cc00-9052-11e9-88fa-c8342079d4b2.jpg)

**Comment by Xeeynamo** [comment]
Thanks for letting me know that. I will keep you updated while the fix is in working.

**Comment by Xeeynamo** [comment]
I still have not found a solution to this problem.

**Comment by ricksanchez6969** [comment]
Don't stress, some things just take time. It's weird, I feel I've been here before though, I dunno like deja Vu kind of thing
