### ISSUE TITLE
Kingdom Hearts HD 1.5 ReMIX (PS3 Support)

### ISSUE THREAD

**Issue by EmreXCoded** [Xeeynamo/KH3SaveEditor#71]
Is KH1FM PS3 support coming in future? That would be much easier as the possible ways for now :/

**Comment by Xeeynamo** [comment]
It should work as long as you have the save decrypted. Try to decrypt it using PS3 Save Bruteforce. I am going to integrate an encryption and decryption feature later on, but do not expect it soon.
