### ISSUE TITLE
KH 3 Pro Code Score

### ISSUE THREAD

**Issue by stvjhr** [Xeeynamo/KH3SaveEditor#75]

**Comment by stvjhr** [comment]
Hi, If possible, can you make a score modifier for KH 3, Pro code ? Like, for story mode in each world and story boss?

**Comment by Xeeynamo** [comment]
Sorry, I never finished the DLC and I never unlocked the Pro codes. But are them not already allowed to be used anywhere in the game?

**Comment by stvjhr** [comment]
hahah, just wan to modified the score if can, its alright, thanks anyway
