### ISSUE TITLE
ability editor not work

### ISSUE THREAD

**Issue by stvjhr** [Xeeynamo/KH3SaveEditor#8]
I want to use the ability editor to give me the ability without do the highscore minigame, when i used the ability editor, it did not give me the ability i already select, how to used the ability editor in your save editor ? please help

**Comment by Xeeynamo** [comment]
Have you tried to select all the check-boxes for the given ability?

**Comment by stvjhr** [comment]
yes, i already select all the boxes in abilities that sora can learn from the highscoring mini game rewards, but when i apply in the save, and load, the abilities not appear. the abilitie are focus syphon from highscorring verum rex, and unison thunder from highscring festive dance.

**Comment by Xeeynamo** [comment]
Did you tried with the latest version? Some of the people on our Discord group says that it is working fine for them. I currently do not have a KH3 copy to test it

**Comment by ricksanchez6969** [comment]
Has this been solved? Just so we have less questions open. I've done the abilities and it seems to be working fine.

**Comment by Xeeynamo** [comment]
@ricksanchez6969 No idea lol. Every one else said that the abilities are working fine. So this is an isolated case to the OP or the abilities that are tight to the minigames results. I am closing this.
