### ISSUE TITLE
KHIII + Re:Mind - Issues with Characters and Records

### ISSUE THREAD

**Issue by AstroGeek946** [Xeeynamo/KH3SaveEditor#82]
I've noticed that Kairi, Aqua and Roxas are not added under Characters in the Kingdom Save Editor since Re:Mind came out 5 months ago, so I hope there's a way to add them. Also, Links and the Hundred Acre Wood mini-games are also not added under Records. I don't have much experiences in programming, so that'll be great if anybody here can add Kairi, Aqua, Roxas, Links and the Hundred Acre Wood mini-games on the Kingdom Save Editor.

**Comment by AstroGeek946** [comment]
Here's my save data that has records of links and the Hundred Acre Wood mini-games. [__data__slot7.zip](https://github.com/Xeeynamo/KH3SaveEditor/files/4809004/__data__slot7.zip)

**Comment by AstroGeek946** [comment]
I forgot to mention other playable characters that should be added under Characters in the Save Editor such as Lea, Terra, Ventus, and Xion. I'll send you my Re:Mind save data whenever I get done with the DLC, so you can hopefully exact data of these characters.

**Comment by Xeeynamo** [comment]
Extra characters from Re:Mind are not stored in the save data.
