### ISSUE TITLE
Edit Game Timer for Kingdom Hearts III

### ISSUE THREAD

**Issue by AstroGeek946** [Xeeynamo/KH3SaveEditor#83]
The save editor program wouldn't allow me to edit the game timer for 'Kingdom Hearts III', so is there a way to fix it?

**Comment by Xeeynamo** [comment]
You are not supposed to modify it as there is no built-in functionality for it. I might look to implement it.

**Comment by Xeeynamo** [comment]
Unfortunately I had to remove the functionality because it was corrupting the save.
