### ISSUE TITLE
Editor tool generate a coruptet sav?

### ISSUE THREAD

**Issue by jimmyM1989** [Xeeynamo/KH3SaveEditor#85]
hello now im shure what my problem is. if i open a sav.bin just open and sav it and upload and unmouted again  and try start KDH3 v1.6 in the savgame menu try to load  in a few seconds cams the fail .. your savdata was destroyed delete?.. pleas cann you help me why that happens?

**Comment by Xeeynamo** [comment]
Hi. Could you pass me a clean save and an edited save? On 27 Jul 2020 18:52, jimmyM1989 <notifications@github.com> wrote:
hello now im shure what my problem is. is i open a sav.bin just open and sav it and upload and unmouted again  and try start KDH3 v1.6 in the savgame menu try to load  in a few seconds cams the fail .. your savdata was destroyed delete?.. pleas cann you help me why that happens?

**Comment by jimmyM1989** [comment]
hello ! thank you for help :)

[Save.zip](https://github.com/Xeeynamo/KH3SaveEditor/files/4983566/Save.zip)

**Comment by jimmyM1989** [comment]
[Save cusa12025.zip](https://github.com/Xeeynamo/KH3SaveEditor/files/4996643/Save.cusa12025.zip)

Hello me again sorry foget to say which cusa it is, in this .zip file is in the hole folder backup from the game KDH called savedata0 and in der folder edit is the .sav file which only saved with your Programm . please do you now why the save. file will be destroyed if i put in the game folder after  unmount and start the ps4 will be delete ? i dont understand it.. :(

**Comment by jimmyM1989** [comment]
> 
> Hi. Could you pass me a clean save and an edited save? On 27 Jul 2020 18:52, jimmyM1989 <notifications@github.com> wrote: hello now im shure what my problem is. is i open a sav.bin just open and sav it and upload and unmouted again and try start KDH3 v1.6 in the savgame menu try to load in a few seconds cams the fail .. your savdata was destroyed delete?.. pleas cann you help me why that happens? —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 
Hello me again sorry foget to say which cusa it is, in this .zip file is in the hole folder backup from the game KDH called savedata0 and in der folder edit is the .sav file which only saved with your Programm . please do you now why the save. file will be destroyed if i put in the game folder after unmount and start the ps4 will be delete ? i dont understand it.. :(
[Save cusa12025.zip](https://github.com/Xeeynamo/KH3SaveEditor/files/4996681/Save.cusa12025.zip)

**Comment by Xeeynamo** [comment]
I am afraid that Playstation Save Mounter does not work with Kingdom Hearts III due to the way the game has been patched to run to 5.05 firmware.

**Comment by jimmyM1989** [comment]
Hello! Thanks for the replay. But I can move the original Save with ps4 mover and upload it working only if ein try to modify and save that data will be corrupted.. Have you any idea how I can get a decrypted save without ps4 save mover? Or maybe a tool that show me what happen / change if i save with the Editor tool?

**Comment by makiakia** [comment]
im using 6.72 and 1.6 save data mounter, i can open khIII save and show properly my save,  munny inventory, and everything, but after save and send back to ps4, save data is corrupted,
i can load if i revert unedited save date to ps4

**Comment by Xeeynamo** [comment]
Hi, is there a 6.72 Save Mounter? I would test it straight away and try to fix it.

**Comment by makiakia** [comment]
https://github.com/GiantPluto/Playstation-4-Save-Mounter/releases

here, giantpluto update ps4 save mounter to 6.72 with ps4debug.bin payload too.
already try mount savegame with or without open KHIII, same result

**Comment by Xeeynamo** [comment]
@jimmyM1989 @makiakia Apparently it is a problem that does not belong to a Save Editor issue:
![image](https://user-images.githubusercontent.com/6128729/90041123-22e21300-dcc9-11ea-91fb-c7f86b3e6f8f.png)

So try to unmount the save and then reboot your console. I am sorry that it caused issues to you.

**Comment by jimmyM1989** [comment]
Hello thanks for help, i trying editing a save file (Fw5.05) like how you said. Mount-editing - Unmount - reboot. Your save file is corruption will be delete... 🙈
Game v. 1.6 is that a problem?
I trying again but i this its same.. This time without changing only save with your tool.

**Comment by jimmyM1989** [comment]
Second trying without changing anything only save the save. File and Unmount and restart it will be destroyed.. But luck.. 🙈 But it don't like update to 6.72 because 5.05 is most stable at the moment.. Maybe if the 7.xx firmware coming i trying again.. Thanks again.

**Comment by Xeeynamo** [comment]
A person from the discord server said he had save corruption by just changing one byte via hex editing. There is something wrong with the save Mounter when you edit stuff. I will try to chase who released the updated version. It might affect 5.05 as well, as you pointed out.

**Comment by jimmyM1989** [comment]
Okey can only waiting if there is possibility to change the Hex value
return after editing that will be great :) i just want  the Ultimakey blade
^^ .  But it's weird in File zila the KByte ist same your right thats
Something with Hex.. Hope you find a way that will really great 🙏

Luciano Ciccariello <notifications@github.com> schrieb am Mi., 12. Aug.
2020, 20:48:

**Comment by Xeeynamo** [comment]
Does anyone of you have Save Wizard too? I wrote on my discord this guide to continue to investigate to the issue:

> Hi everyone. People with a custom firmware discovered that there is an issue with save editing. Now, I do not have the tools to test it right now, but I have a very strong theory on what's happening.
The step to reproduce it are very complicated, but let me explain.
> 1) Use a save where you have at least two slots.
> 2) Decrypt your KH3 save with save wizard of the slot 1 and  send me a copy of it.
> 3) Change only the difficulty with my Save Editor (eg. from Proud to Normal for instance).
> 4) Encrypt it back with Save Wizard and copy the save over your PS4.
> 5) Load the second slot (the one you did not modified the difficulty) and use the save point for the same slot.
> 6) Copy your save to your USB, decrypt it with Save Wizard and send me again your slot 1 save (the one you modified the difficulty)

**Comment by gigantlui** [comment]
> A person from the discord server said he had save corruption by just changing one byte via hex editing. There is something wrong with the save Mounter when you edit stuff. I will try to chase who released the updated version. It might affect 5.05 as well, as you pointed out.<

Hey there,
I tried to add an unedited save to a data where there were only 2 saves and it unmounts the savedata with then 3 saves flawlessly. The corruption happens for some reason exactly in the output file of the Editor (even not changing anything / just open and save again)

best regards

**Comment by Xeeynamo** [comment]
From what I understand, there is a checksum in the save that verify if the save has been edited or not. I was not aware of it when I developed the save editor because Save Wizard was fixing the checksum by itself. Now, without Save Wizard, I have to deal with reimplementing it somehow.

**Comment by Xeeynamo** [comment]
If you have a save that has been damaged due to the process, please send it here and I will recover it. I found the reason why the saves resulted as corrupted.

**Comment by jimmyM1989** [comment]
[slot0 Save to fix.zip](https://github.com/Xeeynamo/KH3SaveEditor/files/5086972/slot0.Save.to.fix.zip)


hello here is my edited sav file to fixing . if possyible pleas cann you fix it? then i unmount it :) Thank you

**Comment by Xeeynamo** [comment]
@jimmyM1989 please let me know if this works :)
[slot0_fixed.zip](https://github.com/Xeeynamo/KH3SaveEditor/files/5089450/slot0_fixed.zip)

**Comment by jimmyM1989** [comment]
Sry.. 🙈 Don't work. After Unmount i restart and try bud same issue save file destroyed.. I try second time delete slot 1 save and slot 2 only slot 0 not working.. :/ hope you find a way :)

**Comment by Xeeynamo** [comment]
@jimmyM1989 @gigantlui @makiakia I fixed it in the latest version of the editor: https://github.com/Xeeynamo/KH3SaveEditor/releases

Thanks a lot for the feedback, I could not have noticed the issue without you :)

**Comment by jimmyM1989** [comment]
Ow yeeah Thank you so much your a gift for the Public community 😎.. I will try soon as possible. 😄

**Comment by jimmyM1989** [comment]
Yeah it reay works great thanks! :D

Jimmy <notifications@github.com> schrieb am Di., 25. Aug. 2020, 10:23:
