### ISSUE TITLE
Level/EXP editor slider?

### ISSUE THREAD

**Issue by Lasareo** [Xeeynamo/KH3SaveEditor#96]
Is there any chance we could get a Level/EXP Slider for the games that have those features? Would make things a lot easier I think :)

**Comment by Xeeynamo** [comment]
Hey, it would be super useful indeed! The only problem with that is that I need to have a list of which amount of EXP corresponds to a specific level. Which is an information that is hard to obtain. Therefore, the EXP text box will remain at the moment. I will eventually consider to add a slider in the future if I have the opportunity to do so.
Thanks for the feedback!
