### ISSUE TITLE
[KH2] Feb1 2006 Prototype support

### ISSUE THREAD

**Issue by RaXZerGamingZ** [Xeeynamo/KH3SaveEditor#98]
* Game name: Kingdom Hearts II Februari 1st 2006 Prototype
* Platform: - (eg. PC, PS2, etc.) PS2

--- insert your feature request description here---
Could be usefull to support this version of KH2. (i tried to attach to pcsx2 and it sais it is unsupported)

**Comment by Xeeynamo** [comment]
Hi, as temporary solution you might be able to boot the game as the final US release, modify what you want there and load the prototype. That build is almost identical to the final build anyway.

**Comment by RaXZerGamingZ** [comment]
i will try that, thank you

**Comment by RaXZerGamingZ** [comment]
Unfortunately it didnt work, i tried with EU and US versions and the Februari 1st save didnt show up

**Comment by Xeeynamo** [comment]
Closing as there is no known way to make it working with KH2US pre-release
