### ISSUE TITLE
KH1(FM) - Ability Modification

### ISSUE THREAD

**Issue by RaXZerGamingZ** [Xeeynamo/KH3SaveEditor#99]
* Game name: - Kingdom Hearts 1 / Kingdom Hearts 1 Final Mix
* Platform: - (eg. PC, PS2, etc.) - Any

--- insert your feature request description here---
To be able to modify characters abilities, only Shared abilities can be modified now.

**Comment by Xeeynamo** [comment]
Hi and thank you for the feedback. Sorry for the long silence, but I can confirm that I implemented this functionality thanks to your suggestion. Expect a new release soon 🔜

![image](https://user-images.githubusercontent.com/6128729/98470641-ff9f0500-21de-11eb-894f-812dea96aa60.png)

**Comment by RaXZerGamingZ** [comment]
Awesome! Thank you very much

**Comment by Xeeynamo** [comment]
Fixed. You can download it the latest release. Thanks for the feedback!
